// Command hero renders the README's hero clip: the four-stream example run as
// an animated GIF, with the library's defaults and nothing else.
//
// It exists so the image at the top of the README is regenerated by one
// command rather than by remembering a set of flags. The defaults are the
// contract — GIFFontSize, 120×36 cells, the derived clip length — so a change
// to the TUI shows up in the hero the next time this is run, and a hero that
// no longer matches the tool is a one-line fix.
//
//	go run ./internal/render/cmd/hero
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/midagedev/toktape/internal/render"
	"github.com/midagedev/toktape/internal/tape"
	"github.com/midagedev/toktape/internal/tui"
)

// heroStreams is the concurrency the hero shows.
const heroStreams = 4

// HeroFPS is the frame rate of the GIF.
//
// Half the library default. The stream phase plays in real time and the run is
// now twenty-six seconds (TTP-28), which at 30 fps is about 2.4 MB — postable,
// but most of it spent on frames nobody can distinguish. At 15 fps the same
// clip is around 1.5 MB and a terminal filling with text reads the same: text
// arrives at twelve tokens a second, so a frame every 67 ms still shows every
// token landing. The mp4, which has no such budget, stays at the library
// default. (Lead decision, 2026-09-13.)
//
// cmd/toktape/render_test.go mirrors this constant — a test binary cannot
// import package main — and checks the published GIF's own timing against it.
const HeroFPS = 15

func main() {
	out := flag.String("out", filepath.Join("assets", "hero.gif"), "where to write the GIF")
	flag.Parse()

	// Four streams, not eight: eight tiles are too busy to read at clip size
	// (user, 2026-09-13). The clip opens on a shell prompt and types the
	// command that produced it, so the stream count here is also the "-n" a
	// viewer sees being typed — internal/render/open.go derives it from this
	// tape rather than from a literal.
	tp := tui.ExampleTapeN(heroStreams)
	// The card's footer names the run file this clip came from. The example
	// run has no file on disk, so the path is derived from its own ID rather
	// than typed in: a hard-coded string would keep showing the old ID after
	// the fixture changed.
	opts := render.Options{FPS: HeroFPS, TapePath: "~/.toktape/runs/" + tp.Summary.ID + tape.Ext}

	if dir := filepath.Dir(*out); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			fail(err)
		}
	}
	start := time.Now()
	if err := render.GIF(tp, opts, *out); err != nil {
		fail(err)
	}
	fi, err := os.Stat(*out)
	if err != nil {
		fail(err)
	}
	sched := render.NewSchedule(render.RunEnd(tp), HeroFPS, 0)
	fmt.Printf("hero %s — %d bytes, %d frames, %v at %d fps (%v)\n",
		*out, fi.Size(), sched.Count, sched.Duration.Round(time.Millisecond), sched.FPS,
		time.Since(start).Round(time.Millisecond))
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "hero:", err)
	os.Exit(1)
}
