// Package ledger keeps the experiment ledger: one tab-separated row per
// recorded run, in <runs dir>/runs.tsv.
//
// A user sweeping -ngl, cache types or concurrency records ten runs and wants
// one table that settles which setting won — pasteable into a spreadsheet,
// greppable, and importable with `toktape log -o sql | sqlite3 runs.db`
// (WriteSQL) or duckdb's read_csv. Not sqlite's own `.import`: it declares
// every column TEXT, so max(decode_tok_s) over 9.1 and 68.4 is "9.1"
// (measured on sqlite 3.51, 2026-09-14).
//
// Design rules:
//
//  1. The tapes are the single source of truth; the ledger is a derived
//     cache. Anything it holds can be regenerated by Rebuild, so a ledger
//     that is missing, stale or hand-damaged is never repaired in place — it
//     is thrown away and rewritten from the tapes.
//  2. Unknown is the empty cell. The human table prints "?" for an
//     unobserved value (the repo rule), but a "?" inside a TSV/CSV/JSON
//     export turns a numeric column into a text one the moment one run did
//     not observe something, so every encoder here writes "" instead.
//  3. Columns are append-only. New columns go at the END so an export taken
//     last month still lines up with one taken today; renaming or moving an
//     existing column is a lead decision.
package ledger

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/midagedev/toktape/internal/card"
	"github.com/midagedev/toktape/internal/tape"
)

// FileName is the ledger's name inside the runs directory.
const FileName = "runs.tsv"

// Columns is the ordered ledger schema. Append new columns only at the END
// so old exports stay column-compatible. Changing an existing column's name
// or position is a lead decision.
var Columns = []string{
	"id", "started_at", "tape", "tag", "note",
	"model", "quant", "params", "size_gb",
	"server", "build",
	"ngl", "flash_attn", "batch", "ubatch", "cache_type_k", "cache_type_v",
	"threads", "override_tensor",
	"concurrency", "prompt_n", "predicted_n",
	"prefill_tok_s", "decode_tok_s", "per_stream_tok_s", "aggregate_tok_s",
	"ttft_ms", "ttft_p50_ms", "ttft_p95_ms", "itl_p50_ms", "itl_p95_ms",
	"cache_label", "cache_n",
	"rss_gb", "vram_gb", "gpus", "load1", "throttled", "contended",
	"warnings", "toktape_version",
	// TTP-78 (2026-09-14): the wall-clock budget and when it actually cut.
	"for_s", "cut_at_s",
}

// colIndex is Columns inverted, so a row can be addressed by column name
// without a linear scan at every lookup.
var colIndex = func() map[string]int {
	m := make(map[string]int, len(Columns))
	for i, c := range Columns {
		m[c] = i
	}
	return m
}()

// Index is the position of a column in a Row, or -1 when the name is not a
// ledger column.
func Index(col string) int {
	if i, ok := colIndex[col]; ok {
		return i
	}
	return -1
}

// Row is one run: one string per column, in Columns order. "" is unknown.
type Row struct {
	Values []string
}

// Get returns the value of one column, or "" when the column is unknown to
// this row (a short row from a hand-edited file reads as unobserved rather
// than panicking).
func (r Row) Get(col string) string {
	i := Index(col)
	if i < 0 || i >= len(r.Values) {
		return ""
	}
	return r.Values[i]
}

// Header is the ledger's first line: the column names, tab-joined.
func Header() string { return strings.Join(Columns, "\t") }

// Encode renders a row as one ledger line. The format has no escape
// character, so a tab, carriage return or newline inside a value (a --note
// with a line break) becomes a space; every value already passed through the
// same rule in FromTape, and this second pass covers rows built by hand.
func Encode(r Row) string {
	v := make([]string, len(Columns))
	for i := range v {
		if i < len(r.Values) {
			v[i] = sanitise(r.Values[i])
		}
	}
	return strings.Join(v, "\t")
}

// FromTape reduces a tape to its ledger row. It is pure: every formatting
// rule of the ledger lives here, so the encoders below only join strings.
//
// Unknown stays "" throughout. A zero that was never measured (no TTFT, no
// cache hits, a rate the server did not report) is unknown and must not be
// written as 0 — a spreadsheet cannot tell an observed zero from a missing
// reading, and the sweep this table exists for would average them together.
func FromTape(tp *tape.Tape) Row {
	r := Row{Values: make([]string, len(Columns))}
	if tp == nil {
		return r
	}
	s := tp.Summary
	set := func(col, v string) {
		if i := Index(col); i >= 0 {
			r.Values[i] = sanitise(v)
		}
	}

	set("id", s.ID)
	if !s.StartedAt.IsZero() {
		// Local time with its offset: the person reading the ledger ran the
		// sweep in their own timezone, and the offset keeps the column
		// sortable and parseable anywhere.
		set("started_at", s.StartedAt.Local().Format(time.RFC3339))
	}
	if s.ID != "" {
		set("tape", s.ID+tape.Ext)
	}
	set("tag", s.Tag)
	set("note", s.Note)

	set("model", modelLabel(s.Model))
	set("quant", s.Model.Quant)
	// The exact parameter count, not a "35 B" label: a unit inside a cell
	// breaks numeric import, which is the whole point of the export rule.
	set("params", int64Str(s.Model.Params))
	set("size_gb", gib1(s.Model.FileBytes))

	if s.Server.Kind != "" && s.Server.Kind != tape.ServerUnknown {
		set("server", string(s.Server.Kind))
	}
	set("build", s.Server.Build)

	f := s.Server.Flags
	set("ngl", f.NGL)
	set("flash_attn", f.FlashAttn)
	set("batch", f.Batch)
	set("ubatch", f.UBatch)
	set("cache_type_k", f.CacheTypeK)
	set("cache_type_v", f.CacheTypeV)
	set("threads", f.Threads)
	set("override_tensor", overrideTensors(f))

	set("concurrency", intStr(s.Concurrency))
	set("prompt_n", intStr(s.Timings.PromptN))
	set("predicted_n", intStr(s.Timings.PredictedN))

	set("prefill_tok_s", num1(s.Timings.PromptPerSecond))
	decode, perStream, aggregate := rates(s)
	set("decode_tok_s", num1(decode))
	set("per_stream_tok_s", num1(perStream))
	set("aggregate_tok_s", num1(aggregate))

	set("ttft_ms", num0(s.Timings.TTFTMs))
	set("ttft_p50_ms", num0(s.Aggregate.TTFTp50Ms))
	set("ttft_p95_ms", num0(s.Aggregate.TTFTp95Ms))
	set("itl_p50_ms", num0(s.Timings.ITLp50Ms))
	set("itl_p95_ms", num0(s.Timings.ITLp95Ms))

	set("cache_label", string(s.Cache.Label))
	set("cache_n", intStr(s.Timings.CacheN))

	set("rss_gb", gib1(s.Memory.AtEnd.RSSBytes))
	set("vram_gb", gib1(vramUsedBytes(s)))
	set("gpus", gpuNames(s))
	set("load1", num1(s.Contention.LoadAvg1))
	set("throttled", boolStr(anyThrottled(s), len(s.GPUsAtEnd) > 0))
	set("contended", boolStr(s.Contention.Contended, contentionObserved(s)))
	// A run with nothing to warn about genuinely has zero warnings, so the
	// count is always written — unlike the measurements above, its zero was
	// observed.
	set("warnings", strconv.Itoa(len(s.Warnings)))
	set("toktape_version", s.ToktapeVersion)
	// What ended the run (TTP-78). A default run ends on a wall clock, so a
	// short row beside a long one is explained by these two cells and by
	// nothing else in the row. cut_at_s larger than for_s is the 64-token
	// floor holding the cut back on a slow box, not an error.
	set("for_s", num1(s.Limit.For.Seconds()))
	set("cut_at_s", num1(s.Limit.CutAt.Seconds()))
	return r
}

// rates picks the three rate columns.
//
// With one stream the server's own predicted_per_second is the decode rate
// and the aggregate is the same figure; the per-stream column stays empty
// because "per stream" says nothing when there is one. With N streams the
// per-stream mean is the decode rate a reader compares against their own
// single-session number, and the aggregate is what the server delivered.
func rates(s tape.RunSummary) (decode, perStream, aggregate float64) {
	if s.Concurrency > 1 {
		return s.Aggregate.PerStreamPredictedPerSecond,
			s.Aggregate.PerStreamPredictedPerSecond,
			s.Aggregate.AggregatePredictedPerSecond
	}
	return s.Timings.PredictedPerSecond, 0, s.Timings.PredictedPerSecond
}

// modelLabel is card.ModelName — the model that ran (2026-09-15, user: "모델이
// 다 실제값으로 찍혀야해"): the variant directory for a shard set, the file's
// stem for one file, never the GGUF header's general.name, which a
// re-quantised variant keeps from the base model. The ledger exports "" for an
// unobserved model, the same empty cell card.ModelName returns.
func modelLabel(m tape.ModelInfo) string {
	return card.ModelName(m)
}

// overrideTensors is the -ot patterns as one cell, verbatim and
// space-separated. internal/card summarises them the same way but keeps the
// helper unexported, so the join is repeated here rather than widening that
// package's API from this track.
func overrideTensors(f tape.ServerFlags) string {
	parts := make([]string, 0, len(f.OverrideTens))
	for _, p := range f.OverrideTens {
		if strings.TrimSpace(p) == "" {
			continue
		}
		parts = append(parts, p)
	}
	return strings.Join(parts, " ")
}

// gpuNames joins the device names with "+" ("RTX 3090+RTX 3090"), dropping
// the vendor prefixes the way the card does.
func gpuNames(s tape.RunSummary) string {
	names := make([]string, 0, len(s.Host.GPUs))
	for _, g := range s.Host.GPUs {
		if n := shortGPUName(g.Name); n != "" {
			names = append(names, n)
		}
	}
	return strings.Join(names, "+")
}

// shortGPUName drops the vendor prefixes nvidia-smi reports. It shortens, it
// never invents. (Mirrors the unexported helper in internal/card.)
func shortGPUName(n string) string {
	n = strings.TrimSpace(n)
	for _, prefix := range []string{"NVIDIA GeForce ", "NVIDIA ", "GeForce ", "AMD ", "Intel "} {
		if strings.HasPrefix(n, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(n, prefix))
		}
	}
	return n
}

// vramUsedBytes is the VRAM in use across every device at the end of the run,
// the same figure the card prints per device.
func vramUsedBytes(s tape.RunSummary) int64 {
	var total int64
	for _, g := range s.GPUsAtEnd {
		total += g.UsedBytes
	}
	return total
}

func anyThrottled(s tape.RunSummary) bool {
	for _, g := range s.GPUsAtEnd {
		if g.Throttled {
			return true
		}
	}
	return false
}

// contentionObserved reports whether anything about the machine's load was
// actually read. A tape recorded with no /proc view carries an all-zero
// ContentionInfo, and writing "0" for it would claim a quiet machine nobody
// measured.
func contentionObserved(s tape.RunSummary) bool {
	c := s.Contention
	return c.Contended || c.LoadAvg1 > 0 || len(c.Reasons) > 0 || c.OtherGPUProcs > 0
}

// sanitise makes a value safe for a line-oriented, tab-separated file.
func sanitise(v string) string {
	if !strings.ContainsAny(v, "\t\r\n") {
		return v
	}
	return strings.NewReplacer("\t", " ", "\r", " ", "\n", " ").Replace(v)
}

// num1 renders a measurement with one decimal; an unobserved 0 stays empty.
func num1(v float64) string {
	if v <= 0 {
		return ""
	}
	return strconv.FormatFloat(v, 'f', 1, 64)
}

// num0 renders a millisecond figure as an integer; an unobserved 0 stays empty.
func num0(v float64) string {
	if v <= 0 {
		return ""
	}
	return strconv.FormatFloat(v, 'f', 0, 64)
}

// gib1 renders a byte count in gibibytes with one decimal. The column names
// say _gb, but the base is 2^30 so the ledger agrees with the card rather
// than disagreeing with it by 7%.
func gib1(b int64) string {
	if b <= 0 {
		return ""
	}
	return strconv.FormatFloat(float64(b)/(1<<30), 'f', 1, 64)
}

func intStr(n int) string {
	if n <= 0 {
		return ""
	}
	return strconv.Itoa(n)
}

func int64Str(n int64) string {
	if n <= 0 {
		return ""
	}
	return strconv.FormatInt(n, 10)
}

// boolStr writes a flag as 1/0, or empty when it was never observed.
func boolStr(v, observed bool) string {
	if !observed {
		return ""
	}
	if v {
		return "1"
	}
	return "0"
}

// StaleError says the ledger on disk does not match what this build writes,
// or is malformed. The tapes are the source of truth, so the fix is always a
// Rebuild rather than an edit.
type StaleError struct {
	Path   string
	Reason string
}

func (e *StaleError) Error() string {
	return fmt.Sprintf("%s: %s", e.Path, e.Reason)
}

// IsStale reports whether err means "throw the ledger away and rebuild it
// from the tapes".
func IsStale(err error) bool {
	var s *StaleError
	return errors.As(err, &s)
}
